### ISSUE TITLE
Runtime not exactly 30 seconds

### ISSUE THREAD

**Issue by melfnie** [matiasandina/homecage_quantification#31]
Run function in trigger_thermal.py takes time to run; find way to account for time cost, then take care of delay.

```
time.sleep(self.seconds_delay)
```

Here, seconds_delay = 30, but the effective delay from running the code will be slightly longer. The interval will be the same every time but it will get further and further from the desired timestamps.

**Comment by matiasandina** [comment]
I think this is working as expected
